api:
  endpoint: "https://api.openai.com/v1"
  key: ""
  model: "gpt-3.5-turbo"
  max_tokens: 4000
  temperature: 0.7
  timeout: 30
  retry_count: 3

backup:
  enabled: true
  backup_dir: ".backup"
  max_backups: 5
  compress: true
  auto_backup: true
  backup_interval: 3600

file_matching:
  include_patterns:
    - "*.yml"
    - "*.yaml"
  exclude_patterns:
    - ".git/**"
    - "node_modules/**"
    - "venv/**"
  exclude_dirs:
    - ".git"
    - "node_modules"
    - "venv"
    - "__pycache__"
  max_file_size: 10485760

translation:
  chunk_size: 2000
  max_concurrent: 3
  retry_count: 3
  retry_delay: 5

blacklist:
  words:
    - "API"
    - "URL"
    - "HTTP"
    - "SDK"
    - "ID"
  patterns:
    - '\\${.*?}'
    - '\\{{.*?}}'
  case_sensitive: false
  preserve_case: true

prompts:
  default: >
    请将以下YAML内容翻译成中文，保持原有格式和结构不变：

    {text}

    注意事项：
    1. 只翻译值，不要翻译键名
    2. 保持原有的缩进和格式
    3. 不要翻译特殊标记（如变量、占位符等）
    4. 保持原有的注释，但将注释内容翻译成中文
  templates: []

progress:
  save_interval: 30
  save_path: ".progress"
  auto_resume: true
  keep_history: true
  backup: true
  backup_suffix: ".bak"

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "yaml_translator.log"
  max_size: 10485760
  backup_count: 5

yaml:
  preserve_quotes: true
  preserve_comments: true
  indent: 2
  width: 80
  allow_unicode: true
  default_flow_style: false

display:
  show_progress: true
  show_status: true
  show_errors: true
  refresh_rate: 0.1
  use_colors: true
  status_format: "[{task}] {status}"
  error_format: "[red]错误: {error}[/]"

retry:
  max_retries: 3
  initial_delay: 1.0
  max_delay: 60.0
  backoff_factor: 2.0
  jitter: true
  retry_on_timeout: true
  retry_on_connection_error: true 