api:
  endpoint: "https://api.openai.com/v1"
  key: ""  # 需要用户提供
  model: "gpt-3.5-turbo"
  max_tokens: 4000
  temperature: 0.7
  timeout: 30  # API请求超时时间（秒）
  retry_count: 3  # API请求重试次数

file_matching:
  include_patterns: ["*.yml", "*.yaml"]
  exclude_patterns: [".git/**", "node_modules/**", "venv/**"]
  exclude_dirs: [".git", "node_modules", "venv", "__pycache__"]
  max_file_size: 10485760  # 10MB，超过此大小的文件将被分块处理

translation:
  chunk_size: 2000  # 每块最大字符数
  max_concurrent: 3  # 并发翻译数
  retry_count: 3    # 重试次数
  retry_delay: 5    # 重试延迟（秒）
  
blacklist:
  words: ["API", "URL", "HTTP", "SDK", "ID"]
  patterns: ["\\$\\{.*?\\}", "\\{\\{.*?\\}\\}"]  # 正则表达式
  case_sensitive: false
  preserve_case: true  # 保持原有大小写

prompts:
  default: |
    请将以下YAML内容翻译为中文，遵循以下规则：
    1. 保持所有键名不变
    2. 只翻译值部分
    3. 保持原有格式和缩进
    4. 保持特殊标记和变量不变
    5. 使用专业、正式的中文表述
  templates:
    - name: "technical"
      content: |
        这是技术文档翻译，请遵循以下规则：
        1. 使用技术领域的专业术语
        2. 保持专业性和准确性
        3. 保持原有格式和标记
    - name: "general"
      content: |
        这是普通文本翻译，请遵循以下规则：
        1. 使用通俗易懂的语言
        2. 保持语言流畅自然
        3. 适当本地化表述

progress:
  save_interval: 30  # 进度保存间隔（秒）
  save_path: ".progress"  # 进度文件保存路径
  auto_resume: true  # 是否自动恢复
  keep_history: true  # 保留历史记录
  backup: true  # 是否备份原文件
  backup_suffix: ".bak"  # 备份文件后缀

logging:
  level: "INFO"  # 日志级别：DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "yaml_translator.log"
  max_size: 10485760  # 10MB
  backup_count: 5  # 保留的日志文件数量 